package com.auction.model;//package com.machinecoding.cab;

public class User extends Person {
	
	int id; //will make autogenerated later
    String phone;
    String email;


	public User(int id, String name) {
		super(name);
		this.id = id;

	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
